### ISSUE TITLE
authorise aws account

### ISSUE THREAD

**Issue by peewee** [rodneylab/svelte-backblaze#1]
re: rodneylab/sveltekit-s3-compatible-storage

what corollary: 
    const authorisationToken = Buffer.from(
      `${S3_COMPATIBLE_ACCOUNT_ID}:${S3_COMPATIBLE_ACCOUNT_AUTH_TOKEN}`,
      'utf-8',
    ).toString('base64');

translated for AWS S3

Basic ${authorisationToken}

**Comment by rodneylab** [comment]
Hey, thanks for reaching out. Could you give more explanation of your issue?

**Comment by peewee** [comment]
hey 
	easy for you but i know nothing of BackBlaze

there are pics of mine on AWS S3 & i’d like to add others
ie upload to AWS

	the authorisation code for BlackBlaze ...

async function authoriseAccount() {
  try {
    const authorisationToken = Buffer.from(
      `${S3_COMPATIBLE_ACCOUNT_ID}:${S3_COMPATIBLE_ACCOUNT_AUTH_TOKEN}`,
      'utf-8',
    ).toString('base64');
 
    const response = await fetch('https://api.backblazeb2.com/b2api/v2/b2_authorize_account', {
      method: 'GET',
      headers: {
        Authorization: `Basic ${authorisationToken}`,


please direct me to complementary AWS code 

Most appreciate your posts, keep it up

Peter Scott

**Comment by rodneylab** [comment]
Hi Peter, I would try the [AWS docs](https://docs.aws.amazon.com/index.html)
